version: '3.8'

services:
  vulnerable:
    build: ./vulnerable-site
    container_name: vulnerable-website
    ports:
      - "5001:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  medium:
    build: ./medium-site
    container_name: medium-website
    ports:
      - "5002:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  secure:
    build: ./secure-site
    container_name: secure-website
    ports:
      - "5003:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: vulnerability-testing